name: "Terraform Azure Infra Deploy"

on:
  push:
    branches:
      - "main"


permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Validate-Plan:
    environment: test
    name: Security Scan & Plan
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      
      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: ./terraform_infra
          soft_fail: true

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        # with:
        #   terraform_version: 

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform_infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform_infra
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform_infra

  Terraform-Deploy:
    name: Infrastructure apply
    runs-on: ubuntu-latest
    environment: production
    needs: Terraform-Validate-Plan

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform_infra

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./terraform_infra
